Fix db/seeds creation of SUSE registry URL record
This currently fails, as the method does not exist:

    NoMethodError: undefined method `find_or_initialize' for #<ActiveRecord::Relation []>